name: VoiceNotes
options:
  bundleIdPrefix: com.voicenotes
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"

targets:
  VoiceNotes:
    type: application
    platform: iOS
    sources:
      - path: VoiceNotes
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: VoiceNotes/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.voicenotes.app
        CODE_SIGN_ENTITLEMENTS: VoiceNotes/VoiceNotes.entitlements
    entitlements:
      path: VoiceNotes/VoiceNotes.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
        com.apple.developer.watchkit: true
    dependencies:
      - target: VoiceNotes Watch App
        embed: true
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage

  VoiceNotesTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: VoiceNotesTests
    dependencies:
      - target: VoiceNotes

  "VoiceNotes Watch App":
    type: application
    platform: watchOS
    sources:
      - path: "VoiceNotes Watch App"
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: "VoiceNotes Watch App/Info.plist"
        PRODUCT_BUNDLE_IDENTIFIER: com.voicenotes.app.watchkitapp
        WK_COMPANION_APP_BUNDLE_IDENTIFIER: com.voicenotes.app
    dependencies: []

  "VoiceNotes Watch AppTests":
    type: bundle.unit-test
    platform: watchOS
    sources:
      - path: "VoiceNotes Watch AppTests"
    dependencies:
      - target: "VoiceNotes Watch App"
