name: tcord
options:
  bundleIdPrefix: ai.2389.tcord
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: HD9NM9NSMK

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"

targets:
  tcord:
    type: application
    platform: iOS
    sources:
      - path: tcord
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: tcord/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: ai.2389.tcord
        CODE_SIGN_ENTITLEMENTS: tcord/tcord.entitlements
    entitlements:
      path: tcord/tcord.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
    dependencies:
      - target: tcord Watch App
        embed: true
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage

  tcordTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: tcordTests
    dependencies:
      - target: tcord

  "tcord Watch App":
    type: application
    platform: watchOS
    sources:
      - path: "tcord Watch App"
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: "tcord Watch App/Info.plist"
        PRODUCT_BUNDLE_IDENTIFIER: ai.2389.tcord.watchkitapp
        WK_COMPANION_APP_BUNDLE_IDENTIFIER: ai.2389.tcord
    dependencies:
      - sdk: AVFoundation.framework

  "tcord Watch AppTests":
    type: bundle.unit-test
    platform: watchOS
    sources:
      - path: "tcord Watch AppTests"
    dependencies:
      - target: "tcord Watch App"
